name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # 使用 Java 17 而不是 11
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # 使用替代的 Android SDK 设置方案
    - name: Set up Android SDK
      uses: android-actions/setup-android-sdk@v1.0.3
      with:
        # 指定需要的 SDK 组件
        sdk-packages: |
          build-tools;30.0.3
          platform-tools
          platforms;android-30
          cmdline-tools;latest
          ndk;21.4.7075529

    - name: Make Gradle Wrapper executable
      run: chmod +x ./gradlew

    # 接受 Android 许可证
    - name: Accept Android Licenses
      run: |
        yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses || true

    - name: Build with Gradle 5.4.1
      run: |
        ./gradlew wrapper --gradle-version 5.4.1
        ./gradlew assembleDebug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: app-debug-apk
        path: app/build/outputs/apk/**/*.apk
        retention-days: 5

    # 缓存优化 (可选)
    - name: Cache Gradle
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
